### ISSUE TITLE
need to be able to logout

### ISSUE THREAD

**Issue by robertIanClarkson** [sfsu-csc-667-fall-2018/Spades-Online-Multiplayer-Website#58]

**Comment by robertIanClarkson** [comment]
Completed just never got around to closing issue after end of semester.

**Comment by Nakul00** [comment]
Hi, there was no other way to contact you. Actually, I was referring to your spades game for my project. I executed the code but I am not able to login. The page keeps on loading once I submit register. Can you please help me with this?
